"""Initial migration - Create log_entries and analysis_results tables.

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create log_entries table
    op.create_table(
        'log_entries',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('log_hash', sa.String(length=64), nullable=False),
        sa.Column('source', sa.String(length=100), nullable=False),
        sa.Column('level', sa.String(length=20), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('message_preview', sa.String(length=500), nullable=True),
        sa.Column('has_analysis', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('log_hash')
    )
    
    # Create indexes for log_entries
    op.create_index('idx_log_entries_created_at', 'log_entries', ['created_at'], unique=False)
    op.create_index('idx_log_entries_level', 'log_entries', ['level'], unique=False)
    op.create_index('idx_log_entries_log_hash', 'log_entries', ['log_hash'], unique=False)
    op.create_index('idx_log_entries_source', 'log_entries', ['source'], unique=False)
    op.create_index('idx_log_entries_timestamp', 'log_entries', ['timestamp'], unique=False)
    
    # Create analysis_results table
    op.create_table(
        'analysis_results',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('log_entry_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('root_cause', sa.Text(), nullable=False),
        sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('processing_time_ms', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['log_entry_id'], ['log_entries.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('log_entry_id')
    )
    
    # Create indexes for analysis_results
    op.create_index('idx_analysis_results_analyzed_at', 'analysis_results', ['analyzed_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes for analysis_results
    op.drop_index('idx_analysis_results_analyzed_at', table_name='analysis_results')
    
    # Drop analysis_results table
    op.drop_table('analysis_results')
    
    # Drop indexes for log_entries
    op.drop_index('idx_log_entries_timestamp', table_name='log_entries')
    op.drop_index('idx_log_entries_source', table_name='log_entries')
    op.drop_index('idx_log_entries_log_hash', table_name='log_entries')
    op.drop_index('idx_log_entries_level', table_name='log_entries')
    op.drop_index('idx_log_entries_created_at', table_name='log_entries')
    
    # Drop log_entries table
    op.drop_table('log_entries')
    
    # ### end Alembic commands ###
