"""Remove severity column in analysis table

Revision ID: b9807546a92c
Revises: 001
Create Date: 2026-02-13 01:24:20.817802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9807546a92c'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_analysis_results_analyzed_at', table_name='analysis_results')
    op.drop_index('idx_analysis_results_severity', table_name='analysis_results')
    op.drop_column('analysis_results', 'suggestions')
    op.drop_column('analysis_results', 'severity')
    op.drop_index('idx_log_entries_level', table_name='log_entries')
    op.drop_index('idx_log_entries_log_hash', table_name='log_entries')
    op.drop_index('idx_log_entries_source', table_name='log_entries')
    op.drop_index('idx_log_entries_timestamp', table_name='log_entries')
    op.drop_constraint('log_entries_log_hash_key', 'log_entries', type_='unique')
    op.create_index(op.f('ix_log_entries_level'), 'log_entries', ['level'], unique=False)
    op.create_index(op.f('ix_log_entries_log_hash'), 'log_entries', ['log_hash'], unique=True)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_log_hash'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_level'), table_name='log_entries')
    op.create_unique_constraint('log_entries_log_hash_key', 'log_entries', ['log_hash'])
    op.create_index('idx_log_entries_timestamp', 'log_entries', ['timestamp'], unique=False)
    op.create_index('idx_log_entries_source', 'log_entries', ['source'], unique=False)
    op.create_index('idx_log_entries_log_hash', 'log_entries', ['log_hash'], unique=False)
    op.create_index('idx_log_entries_level', 'log_entries', ['level'], unique=False)
    op.add_column('analysis_results', sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('analysis_results', sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('idx_analysis_results_severity', 'analysis_results', ['severity'], unique=False)
    op.create_index('idx_analysis_results_analyzed_at', 'analysis_results', ['analyzed_at'], unique=False)
    # ### end Alembic commands ###
