"""Create tables

Revision ID: 5755d43bdf4d
Revises: b14572114232
Create Date: 2026-03-06 01:03:04.572372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5755d43bdf4d'
down_revision: Union[str, None] = 'b14572114232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_preview', sa.String(length=500), nullable=True),
    sa.Column('has_analysis', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_entries_created_at', 'log_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_log_entries_level'), 'log_entries', ['level'], unique=False)
    op.create_index(op.f('ix_log_entries_log_hash'), 'log_entries', ['log_hash'], unique=True)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_entry_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_entry_id'], ['log_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_log_hash'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_level'), table_name='log_entries')
    op.drop_index('idx_log_entries_created_at', table_name='log_entries')
    op.drop_table('log_entries')
    # ### end Alembic commands ###
